version: '3.3'
services:
  node_basic:
    image: dimg/node_basic
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
